import type { CSSProperties } from 'react';

// Theme-aware color fallback chains. When the chat host provides its own
// `--color-*` variables those win; otherwise we fall back to the explicit
// `--app-*` palette set by AppShell (which stays contrasty in dark mode),
// and finally to a neutral grey so the UI never disappears entirely.
const FG = 'var(--color-text-primary, var(--app-fg, inherit))';
const BORDER = 'var(--color-border-primary, var(--app-border, rgba(127,127,127,0.25)))';
const BORDER_FAINT = 'var(--color-border-primary, var(--app-border, rgba(127,127,127,0.15)))';
const SURFACE = 'var(--color-background-secondary, var(--app-surface, rgba(127,127,127,0.08)))';
const SURFACE_2 = 'var(--color-background-tertiary, var(--app-surface-2, rgba(127,127,127,0.12)))';
const ACCENT = 'var(--color-accent, var(--app-accent, #2563eb))';

export const styles: Record<string, CSSProperties> = {
  root: {
    fontFamily: 'var(--font-sans, system-ui, sans-serif)',
    color: FG,
    background: 'transparent',
    padding: '12px',
    boxSizing: 'border-box',
  },
  appShell: {
    fontFamily: 'var(--font-sans, system-ui, sans-serif)',
    color: FG,
    background: 'transparent',
    boxSizing: 'border-box',
  },
  appShellHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '8px',
    padding: '6px 12px',
    borderBottom: `1px solid ${BORDER_FAINT}`,
  },
  appShellTitle: {
    fontSize: '12px',
    fontWeight: 600,
    letterSpacing: '0.02em',
    opacity: 0.8,
  },
  appShellToggle: {
    flexShrink: 0,
    width: '22px',
    height: '22px',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    border: `1px solid ${BORDER}`,
    borderRadius: '6px',
    background: SURFACE,
    color: 'inherit',
    cursor: 'pointer',
    fontSize: '11px',
    lineHeight: 1,
    padding: 0,
  },
  appShellBody: {
    padding: '12px',
    boxSizing: 'border-box',
  },
  centered: {
    padding: '20px 12px',
    textAlign: 'center',
    opacity: 0.65,
    fontSize: '13px',
  },
  detailWrap: {
    marginBottom: '12px',
    borderRadius: '8px',
    overflow: 'hidden',
    border: `1px solid ${BORDER}`,
    background: SURFACE,
  },
  detailThumbWrap: {
    position: 'relative',
    aspectRatio: '16 / 9',
    background: SURFACE_2,
  },
  detailThumb: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    display: 'block',
  },
  detailThumbPlaceholder: {
    width: '100%',
    height: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '32px',
    opacity: 0.35,
  },
  detailBody: {
    padding: '10px 12px',
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  detailTitle: {
    fontSize: '14px',
    fontWeight: 600,
    lineHeight: 1.35,
  },
  detailMeta: {
    fontSize: '12px',
    opacity: 0.65,
  },
  detailActions: {
    display: 'flex',
    gap: '8px',
    padding: '8px',
    borderTop: `1px solid ${BORDER}`,
  },
  actionBtn: {
    flex: 1,
    padding: '7px 10px',
    border: `1px solid ${BORDER}`,
    borderRadius: '6px',
    background: SURFACE,
    color: 'inherit',
    cursor: 'pointer',
    fontSize: '12px',
  },
  descriptionWrap: {
    padding: '10px 12px',
    borderTop: `1px solid ${BORDER}`,
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  descriptionText: {
    fontSize: '13px',
    lineHeight: 1.5,
    whiteSpace: 'pre-wrap',
    wordBreak: 'break-word',
  },
  descriptionTextClamped: {
    display: '-webkit-box',
    WebkitLineClamp: 3,
    WebkitBoxOrient: 'vertical',
    overflow: 'hidden',
  },
  descriptionToggle: {
    alignSelf: 'flex-start',
    border: 'none',
    background: 'transparent',
    color: ACCENT,
    cursor: 'pointer',
    fontSize: '12px',
    fontWeight: 600,
    padding: 0,
  },
  subtitlesSection: {
    borderTop: `1px solid ${BORDER}`,
    background: 'transparent',
  },
  subtitleSearchRow: {
    position: 'relative',
    padding: '6px 8px',
    borderBottom: `1px solid ${BORDER_FAINT}`,
    flexShrink: 0,
  },
  subtitleSearchInput: {
    width: '100%',
    padding: '5px 34px 5px 8px',
    borderRadius: '5px',
    border: `1px solid ${BORDER}`,
    background: SURFACE,
    color: 'inherit',
    outline: 'none',
    fontSize: '11px',
    boxSizing: 'border-box',
  },
  subtitleMatchCount: {
    position: 'absolute',
    top: '11px',
    right: '16px',
    fontSize: '10px',
    opacity: 0.55,
    pointerEvents: 'none',
  },
  subtitlesPanel: {
    maxHeight: '150px',
    overflowY: 'auto',
  },
  subtitlesMessage: {
    padding: '10px 12px',
    fontSize: '12px',
    opacity: 0.6,
    textAlign: 'center',
  },
  cuesList: {
    margin: 0,
    padding: '6px 0',
    listStyle: 'none',
  },
  cueItem: {
    display: 'flex',
    gap: '8px',
    alignItems: 'flex-start',
    padding: '5px 12px',
    fontSize: '12px',
    lineHeight: 1.45,
  },
  cueItemActive: {
    background: SURFACE_2,
  },
  cueItemDimmed: {
    opacity: 0.35,
  },
  highlight: {
    background: ACCENT,
    color: '#fff',
    borderRadius: '2px',
    padding: '0 1px',
  },
  cueTime: {
    flexShrink: 0,
    border: 'none',
    borderRadius: '4px',
    padding: '2px 6px',
    background: SURFACE,
    color: ACCENT,
    fontFamily: 'var(--font-mono, ui-monospace, monospace)',
    fontSize: '11px',
    cursor: 'pointer',
    textDecoration: 'underline',
    textUnderlineOffset: '2px',
  },
  cueText: {
    flex: 1,
    wordBreak: 'break-word',
  },
  loadMoreRow: {
    padding: '8px',
    textAlign: 'center',
    borderTop: `1px solid ${BORDER_FAINT}`,
  },
  loadSubtitlesRow: {
    padding: '12px',
    textAlign: 'center',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '8px',
  },
  loadMoreBtn: {
    padding: '6px 14px',
    borderRadius: '6px',
    border: `1px solid ${BORDER}`,
    background: SURFACE,
    color: 'inherit',
    fontSize: '12px',
    cursor: 'pointer',
  },
  failure: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
    fontSize: '12px',
  },
  failureText: {
    margin: 0,
    fontSize: '13px',
    lineHeight: 1.45,
  },
  trackPicker: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
    padding: '8px 8px 4px',
    borderBottom: `1px solid ${BORDER_FAINT}`,
  },
  trackGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    flexWrap: 'wrap',
  },
  trackGroupLabel: {
    fontSize: '10px',
    fontWeight: 600,
    opacity: 0.55,
    textTransform: 'uppercase',
    letterSpacing: '0.04em',
    flexShrink: 0,
    minWidth: '48px',
  },
  trackPills: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '4px',
  },
  trackPill: {
    padding: '2px 8px',
    borderRadius: '999px',
    border: `1px solid ${BORDER}`,
    background: SURFACE,
    color: 'inherit',
    fontSize: '11px',
    cursor: 'pointer',
    lineHeight: 1.4,
  },
  trackPillActive: {
    borderColor: ACCENT,
    background: SURFACE_2,
    color: ACCENT,
    fontWeight: 600,
  },
  trackSelect: {
    flex: 1,
    minWidth: 0,
    padding: '4px 8px',
    borderRadius: '6px',
    border: `1px solid ${BORDER}`,
    background: SURFACE,
    color: 'inherit',
    fontSize: '11px',
    cursor: 'pointer',
  },
  carousel: {
    display: 'flex',
    gap: '10px',
    overflowX: 'auto',
    margin: 0,
    padding: '0 0 4px',
    listStyle: 'none',
    scrollSnapType: 'x mandatory',
    WebkitOverflowScrolling: 'touch',
  },
  cardItem: {
    flex: '0 0 200px',
    scrollSnapAlign: 'start',
  },
  card: {
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    border: `1px solid ${BORDER}`,
    borderRadius: '8px',
    overflow: 'hidden',
    background: SURFACE,
    cursor: 'pointer',
    textAlign: 'left',
    padding: 0,
    color: 'inherit',
  },
  cardActive: {
    borderColor: ACCENT,
  },
  thumbWrap: {
    position: 'relative',
    aspectRatio: '16 / 9',
    background: SURFACE_2,
  },
  thumb: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    display: 'block',
  },
  thumbPlaceholder: {
    width: '100%',
    height: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '24px',
    opacity: 0.35,
  },
  duration: {
    position: 'absolute',
    bottom: '6px',
    right: '6px',
    background: 'rgba(0,0,0,0.72)',
    color: '#fff',
    fontSize: '10px',
    padding: '2px 5px',
    borderRadius: '4px',
  },
  cardBody: {
    padding: '8px 10px 10px',
    display: 'flex',
    flexDirection: 'column',
    gap: '3px',
  },
  title: {
    fontSize: '13px',
    fontWeight: 600,
    lineHeight: 1.3,
    display: '-webkit-box',
    WebkitLineClamp: 2,
    WebkitBoxOrient: 'vertical',
    overflow: 'hidden',
  },
  meta: {
    fontSize: '11px',
    opacity: 0.65,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
};
